### ISSUE TITLE
Support document types (pdf/csv/...) in Converse API

### ISSUE THREAD

**Issue by roman-romanov-o** [epam/ai-dial-adapter-bedrock#198]
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ContentBlock.html

Converse API allow you to pass [Document Block](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_DocumentBlock.html):

possible types:
```
pdf | csv | doc | docx | xls | xlsx | html | txt | md
```

Enable documents for Amazon Nova / Claude Sonnet (?) models

**Comment by adubovik** [comment]
Resolved by https://github.com/epam/ai-dial-adapter-bedrock/pull/199

**Comment by adubovik** [comment]
Resolved by https://github.com/epam/ai-dial-adapter-bedrock/pull/199
