### ISSUE TITLE
max_tokens parameter is ignored by claude 3 models

### ISSUE THREAD

**Issue by vcharnahrebel** [epam/ai-dial-adapter-bedrock#96]
max_tokens request parameter is ignored, response defaults to 512 default.

Steps to reproduce: 
1) Call deployments/anthropic.claude-v3-haiku/chat/completions with the following request: 
{
    "messages": [
      {
        "role": "user",
        "content": "generate a two thousand words poem"
      }
    ],
    "temperature": 0.5,
    "max_tokens" : 1,
    "stream":false
}
2) Observe that response still has 512 tokens

**Comment by adubovik** [comment]
@vcharnahrebel the bug is fixed in the development. It was caused by an unfortunate typo.
